name: TerminalGPT-CICD

on:
  push:
    branches: [ release ]

jobs:
  create_release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Specify the .NET 6 SDK here

      - name: Build with dotnet
        run: dotnet publish --configuration Release --output ./published

      - name: Zip published directory
        run: |
          Compress-Archive -Path ./published/* -DestinationPath ./Terminal-GPT.zip

      - name: Create tag
        id: create_tag
        run: |
          $VERSION = [int][double]::Parse((Get-Date (Get-Date).ToUniversalTime() -UFormat %s))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git config user.email "johnpaul@niswonger.tech"
          git config user.name "LemonDrop1228"
          git tag $VERSION
          git push origin --tags

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RECIPE: '1. Preheat oven to 350 degrees F (175 degrees C).\n2. Cream together the butter, white sugar, and brown sugar until smooth.\n3. Beat in the eggs one at a time, then stir in the vanilla.\n4. Dissolve baking soda in hot water. Add to batter along with salt.\n5. Stir in flour, chocolate chips, and nuts.\n6. Drop by large spoonfuls onto ungreased pans.\n7. Bake for about 10 minutes in the preheated oven, or until edges are nicely browned.'
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: ${{ env.RECIPE }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Terminal-GPT.zip
          asset_name: Terminal-GPT.zip
          asset_content_type: application/zip
